In [2]:
import numpy as np

In [13]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
path='Canada.xlsx'

In [5]:
df=pd.read_excel(path,skiprows=range(20))

In [6]:
df.head()

,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1,NaN
1,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846,NaN
2,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602,NaN
3,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453,NaN
4,Immigrants,Foreigners,Africa,Southern Africa,1041,1126,791,387,297,327,...,1203,1012,1148,1230,1184,1235,1306,1049,1348,NaN

In [7]:
df.set_index(df.RegName,inplace=True,drop=True,append=False)

In [8]:
df.head()

,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
RegName,,,,,,,,,,,,,,,,,,,,,
Northern America,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1,NaN
Eastern Africa,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846,NaN
Middle Africa,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602,NaN
Northern Africa,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453,NaN
Southern Africa,Immigrants,Foreigners,Africa,Southern Africa,1041,1126,791,387,297,327,...,1203,1012,1148,1230,1184,1235,1306,1049,1348,NaN

In [14]:
years=list(map(str,range(1980,2014)))
df.loc['AreaName',years].plot(kind='line')
plt.xlabel('Years')
plt.ylabel('Number of immigration')
plt.title('Immigration from Haiti')

KeyError: 'AreaName'